version: '3.7'
services:
  yolov4_cpu:
    build:
      context: .
      dockerfile: Dockerfile
      target: develop
    environment:
      DISPLAY:
      TF_FORCE_GPU_ALLOW_GROWTH: 'true'
      QT_X11_NO_MITSHM: 1
    image: yolov4_cpu:maxwell
#    stdin_open: true
#    tty: true
    # set user to your user id which is usually 1000:1000 to check you user id run `echo $(id -u):$(id -g)`
    user: 1000:1000
    volumes:
      # passing through this file allows opening windows from the container in your host computer
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      # pass the passwd file so it can know who user 1000 is
      - "/etc/passwd:/etc/passwd"
      # pass through data folder
      - "/opt/data:/opt/data"
      # pass through the .keras folder
      - "/opt/data/.keras:/tmp/.keras"
      # mount our project in the container
      - ".:/opt/project"
    working_dir: /opt/project
#    command:
#      - src/save_model.py
#      - src/save_model.py --weights ./data/yolov4.weights --output ./checkpoints/yolov4-416 --input_size 416 --model yolov4